# Generated by Django 4.0.4 on 2022-04-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='no color', max_length=255),
            preserve_default=False,
        ),
    ]
