# Generated by Django 4.0.4 on 2022-04-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_car_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model']},
        ),
    ]
